name: Docker build & push
on:
  push:
    branches:
    - main

jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Set build start time
          run: echo "BUILD_START_TIME=$(date +'%s')" >> $GITHUB_ENV
        
        - name: Login to ACR
          uses: docker/login-action@v1
          with:
            registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/petstorepetservice:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/petstorepetservice:${{ github.sha }}
        - name: Change image tag in deployments
          uses: actions/checkout@v2
        - run: bash .github/workflows/git.sh ${{ secrets.GHE_TOKEN }} "${{ secrets.REGISTRY_LOGIN_SERVER }}\/petstorepetservice:${{ github.sha }}" ${{ github.ref }}
        
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          continue-on-error: true
          with:
            image-ref: '${{ secrets.REGISTRY_LOGIN_SERVER }}/petstorepetservice:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'MEDIUM,HIGH,CRITICAL'

        - name: Get DI dependencies
          run: |
            git clone --depth 1 https://${{secrets.GHE_TOKEN}}@github.kyndryl.net/MCMP-DevOps-Intelligence/scripts.git -b priyanshi-patch-1 $RUNNER_TEMP/scripts
          if: ${{ always() }}

        - name: Publish to Devops Intelligence
          shell: bash
          env:
            APPNAME: petstorepetservice
            GITHUB_SHA: ${{ github.sha }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            BUILD_STATUS: ${{ job.status }}
            DEV_SECOPS_HOST_TOKEN: ${{ secrets.DEV_SECOPS_HOST_TOKEN}}
            # INSTALL_DIR: ${{ github.workspace }}/bin
            IS_PULL_REQUEST: ${{ github.event.number }}
          if: ${{ always() }}
          run: | # if no args, it will consider all tools, else you can specify names as arg. Supported args - image, license, build
            $RUNNER_TEMP/scripts/publish